from flask import Flask, request, jsonify, render_template
import random

app = Flask(__name__)

# Function to load dialogs from the file
def load_dialogs(file_path):
    dialogs = {}
    with open(file_path, 'r') as file:
        for line in file:
            question, answer = line.strip().split('\t')
            dialogs[question.lower()] = answer
    return dialogs

# Function to get a response from the dialogs
def get_response(user_input, dialogs):
    user_input = user_input.lower().strip()
    if user_input in dialogs:
        return dialogs[user_input]
    elif "hello" in user_input:
        return "Hello! How can I assist you today?"
    elif "how are you" in user_input:
        return "I'm a chatbot, so I'm always good! How can I help you?"
    elif "your name" in user_input:
        return "I am ChatGPT, your friendly assistant."
    elif "time" in user_input:
        return "I'm not equipped with a clock, but you can check the time on your device."
    elif "weather" in user_input:
        return "I can't provide live weather updates, but you can check a weather website or app."
    elif "bye" in user_input or "goodbye" in user_input:
        return "Goodbye! Have a great day!"
    elif "what is your purpose" in user_input:
        return "My purpose is to assist you with any questions or tasks you have."
    elif "who created you" in user_input:
        return "I was created by OpenAI to help with various tasks and answer questions."
    elif "what can you do" in user_input:
        return "I can answer questions, provide information, and assist with many tasks."
    elif "where are you from" in user_input:
        return "I'm a virtual assistant created by OpenAI, so I exist in the digital world."
    elif "tell me a joke" in user_input:
        return "Why don't scientists trust atoms? Because they make up everything!"
    elif "what is the capital of France" in user_input:
        return "The capital of France is Paris."
    elif "how old are you" in user_input:
        return "I don't have an age like humans do. I'm a virtual assistant."
    elif "can you help me" in user_input:
        return "Of course! I'm here to help you with any questions or tasks you have."
    elif "what is your favorite color" in user_input:
        return "I don't have a favorite color, but I think all colors are great!"
    elif "do you have any hobbies" in user_input:
        return "I don't have hobbies like humans, but I enjoy helping people."
    elif "what is your favorite food" in user_input:
        return "I don't eat food, but I think all foods are interesting."
    elif "do you have friends" in user_input:
        return "I don't have friends like humans, but I interact with many users like you."
    elif "what do you like to do" in user_input:
        return "I like to assist users with their questions and tasks."
    elif "can you tell me a story" in user_input:
        return "Once upon a time, in a land far away, there was a chatbot that loved to help people..."
    elif "what is the meaning of life" in user_input:
        return "That's a deep question! Many people believe the meaning of life is to find happiness and fulfillment."
    elif "what is 2+2" in user_input:
        return "2+2 is 4."
    elif "what is the largest planet" in user_input:
        return "The largest planet in our solar system is Jupiter."
    elif "do you know any fun facts" in user_input:
        return "Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3000 years old and still edible."
    elif "how do airplanes fly" in user_input:
        return "Airplanes fly due to the lift generated by their wings. The shape of the wings creates a difference in air pressure, allowing the plane to stay in the air."
    elif "who is the president of the United States" in user_input:
        return "As of 2024, the president of the United States is Joe Biden."
    elif "what is the tallest mountain" in user_input:
        return "The tallest mountain in the world is Mount Everest, which is about 29,032 feet (8,848 meters) high."
    elif "do you have any pets" in user_input:
        return "I don't have pets, but I think animals are fascinating."
    elif "can you play music" in user_input:
        return "I can't play music, but you can listen to music on various streaming services."
    elif "what is your favorite book" in user_input:
        return "I don't read books like humans, but I think all books have something interesting to offer."
    elif "what is your favorite movie" in user_input:
        return "I don't watch movies, but I can help you find information about them."
    elif "can you dance" in user_input:
        return "I can't dance, but I think dancing is a great way to have fun and express yourself."
    elif "what is the speed of light" in user_input:
        return "The speed of light in a vacuum is approximately 299,792,458 meters per second (about 186,282 miles per second)."
    elif "do you believe in aliens" in user_input:
        return "As a chatbot, I don't have beliefs, but the possibility of extraterrestrial life is a fascinating topic that scientists are exploring."
    elif "what is your favorite animal" in user_input:
        return "I don't have a favorite animal, but I think all animals are amazing in their own ways."
    elif "can you help me with my homework" in user_input:
        return "I can try to help you with your homework. What do you need help with?"
    elif "do you like sports" in user_input:
        return "I don't play sports, but I think they are a great way to stay active and have fun."
    elif "what is your favorite sport" in user_input:
        return "I don't have a favorite sport, but I can provide information about many different sports."
    elif "can you drive a car" in user_input:
        return "I can't drive a car, but I can provide information about cars and driving."
    elif "what is your favorite hobby" in user_input:
        return "I don't have hobbies like humans, but I enjoy helping people."
    elif "do you know any riddles" in user_input:
        return "Sure! Here's one: I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I? (Answer: An echo)"
    elif "can you solve math problems" in user_input:
        return "I can try to help with math problems. What do you need help with?"
    elif "do you like music" in user_input:
        return "I don't listen to music like humans, but I think music is a wonderful form of expression."
    elif "what is your favorite song" in user_input:
        return "I don't have a favorite song, but I can help you find information about music."
    elif "can you tell me a fun fact" in user_input:
        return "Sure! Did you know that a group of flamingos is called a 'flamboyance'?"
    elif "what is your favorite TV show" in user_input:
        return "I don't watch TV shows, but I can help you find information about them."
    elif "can you cook" in user_input:
        return "I can't cook, but I can help you find recipes and cooking tips."
    elif "what languages do you speak" in user_input:
        return "I can understand and respond in many languages. Try asking me something in another language!"
    elif "what is your favorite season" in user_input:
        return "I don't experience seasons like humans, but I think each season has its own unique beauty."
    elif "can you tell me the news" in user_input:
        return "I don't have access to live news updates, but you can check news websites or apps for the latest information."
    elif "what is your favorite holiday" in user_input:
        return "I don't celebrate holidays, but I think all holidays are special in their own way."
    elif "what is your favorite movie genre" in user_input:
        return "I don't watch movies, but I think all genres have something interesting to offer."
    elif "do you have any siblings" in user_input:
        return "I don't have siblings like humans, but there are many other chatbots like me."
    elif "can you help me plan a trip" in user_input:
        return "I can provide information and tips for planning a trip. Where would you like to go?"
    elif "what is your favorite dessert" in user_input:
        return "I don't eat food, but I think desserts are a delightful treat."
    elif "can you play games" in user_input:
        return "I can't play games, but I can help you find information about different games."
    elif "what is your favorite game" in user_input:
        return "I don't play games, but I think all games are fun in their own way."
    elif "can you read my mind" in user_input:
        return "I can't read minds, but I can try to help you with any questions or tasks you have."
    elif "do you have a family" in user_input:
        return "I don't have a family like humans, but I interact with many users like you."
    elif "can you help me learn" in user_input:
        return "Absolutely! I can provide information and resources to help you learn. What would you like to learn about?"
    elif "what is your favorite subject" in user_input:
        return "I don't have a favorite subject, but I think all subjects have something interesting to offer."
    elif "can you help me find a job" in user_input:
        return "I can provide tips and resources for job searching. What type of job are you looking for?"
    elif "do you like to travel" in user_input:
        return "I don't travel like humans, but I think traveling is a wonderful way to explore and learn."
    elif "what is your favorite place" in user_input:
        return "I don't have a favorite place, but I think all places have their own unique charm."
    elif "can you help me make a decision" in user_input:
        return "I can provide information and advice to help you make a decision. What do you need help with?"
    elif "what is your favorite animal" in user_input:
        return "I don't have a favorite animal, but I think all animals are fascinating."
    elif "do you know any jokes" in user_input:
        return "Sure! Why did the scarecrow win an award? Because he was outstanding in his field!"
    elif "can you help me with my project" in user_input:
        return "I can provide information and resources to help you with your project. What is your project about?"
    elif "what is your favorite hobby" in user_input:
        return "I don't have hobbies like humans, but I enjoy helping people."
    elif "can you help me with my assignment" in user_input:
        return "I can try to help you with your assignment. What do you need help with?"
    elif "what is your favorite book" in user_input:
        return "I don't read books like humans, but I think all books have something interesting to offer."
    elif "can you tell me a story" in user_input:
        return "Once upon a time, in a land far away, there was a chatbot that loved to help people..."
    elif "what is your purpose" in user_input:
        return "My purpose is to assist you with any questions or tasks you have."
    else:
        return "I'm not sure how to respond to that. Can you ask something else?"

# Load dialogs from the file
file_path = 'dialogs.txt'  # Update the path to your dialogs file
dialogs = load_dialogs(file_path)

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/get_response", methods=["POST"])
def get_chat_response():
    user_input = request.form["user_input"]
    response = get_response(user_input, dialogs)
    return jsonify({"response": response})

if __name__ == "__main__":
    app.run(debug=True)
